### ISSUE TITLE
Running in background

### ISSUE THREAD

**Issue by niltondiniz** [Crdzbird/floaty_chathead#3]
Hi! 
this lib is great!!

Is it possible to open the chathead when closing / kill the app, and close the chathead when reopening the app?

**Comment by Crdzbird** [comment]
Sorry for the long waiting...

It's possible to open the chathead when the app is being killed or is closing, you just need to call the function

`floatyHead.openBubble();`

and the same can be applied for the closing of the bubble.

`floatyHead.closeHead();`

however, for handle those states, currently the plugin doesn't control anything related to the lifecycle of the app, because the chathead works on a different thread unrelated to the mainThread.

Maybe this can help you:
[https://pub.dev/packages/flutter_plugin_android_lifecycle](url)
